/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaiduMap: typeof import('./src/components/SearchUniversity/CollegeInquiry/BaiduMap.vue')['default']
    Carousel: typeof import('./src/components/home/Carousel.vue')['default']
    ChooseInstitution: typeof import('./src/components/SimulatedVolunteering/SearchBar/ChooseInstitution/ChooseInstitution.vue')['default']
    ChooseMajor: typeof import('./src/components/SimulatedVolunteering/SearchBar/ChooseMajor/ChooseMajor.vue')['default']
    CollegeLibrary: typeof import('./src/components/SearchUniversity/CollegeInquiry/CollegeLibrary.vue')['default']
    EstablishingMajors: typeof import('./src/components/SearchUniversity/CollegeDetails/EstablishingMajors.vue')['default']
    FourthLevel: typeof import('./src/components/home/FourthLevel.vue')['default']
    InformationExit: typeof import('./src/components/home/InformationExit.vue')['default']
    InstitutionsList: typeof import('./src/components/SimulatedVolunteering/InstitutionsList/InstitutionsList.vue')['default']
    List: typeof import('./src/components/SimulatedVolunteering/InstitutionsList/List/List.vue')['default']
    Login: typeof import('./src/components/login/Login.vue')['default']
    Membership: typeof import('./src/components/personalInformation/Membership/Membership.vue')['default']
    MessList: typeof import('./src/components/home/MessList.vue')['default']
    MyFavorites: typeof import('./src/components/personalInformation/MyFavorites/MyFavorites.vue')['default']
    PersonalData: typeof import('./src/components/personalInformation/PersonalData/PersonalData.vue')['default']
    PointsLeaderboard: typeof import('./src/components/SearchUniversity/CollegeInquiry/PointsLeaderboard.vue')['default']
    ProfessionalOverview: typeof import('./src/components/InquireMajor/ProfessionalOverview.vue')['default']
    RelatedEmployment: typeof import('./src/components/InquireMajor/RelatedEmployment.vue')['default']
    Result: typeof import('./src/components/Holland/Result/Result.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchoolProfile: typeof import('./src/components/SearchUniversity/CollegeDetails/SchoolProfile.vue')['default']
    ScorePlan: typeof import('./src/components/SearchUniversity/CollegeDetails/ScorePlan.vue')['default']
    SecondLevel: typeof import('./src/components/home/SecondLevel.vue')['default']
    Statement: typeof import('./src/components/home/Statement.vue')['default']
    TableList: typeof import('./src/components/SimulatedVolunteering/TablePreferences/TableList/TableList.vue')['default']
    ThirdLayer: typeof import('./src/components/home/ThirdLayer.vue')['default']
    ToHeaderMenu: typeof import('./src/components/Header/Menu/ToHeaderMenu.vue')['default']
    TopHeader: typeof import('./src/components/Header/TopHeader/TopHeader.vue')['default']
    TopicTest: typeof import('./src/components/Holland/TopicTest/TopicTest.vue')['default']
    TreeVolunteer: typeof import('./src/components/SimulatedVolunteering/TablePreferences/TreeVolunteer/TreeVolunteer.vue')['default']
  }
}
